
# Makefile for SOC driver Library
#

LOCALDIR = src
include ${ROOT_DIR}/make/Make.config

subdirs := common
include ${ROOT_DIR}/make/Make.subdirs


lib = libServoAntAgent
include ${ROOT_DIR}/make/Make.lib

